'use client';

import Card from '@/components/card';

// --- THIS (metadata export) WON'T WORK IN CLIENT COMPONENT
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function StorePage() {
  return (
    <main className="text-7xl">
      <button>Some button</button>
    </main>
  );
}

//
/* 

  1. server components execute on the server*
  2. you cannot access browser specific apis (window, document, localStorage, etc)
      - events ❌


*/
